### ISSUE TITLE
two queries made when returning a collection 

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/ashleygwilliams.github.io#13]
e.g. `GET /writing`

```
{ __cid: '__cid2',
  method: 'columnInfo',
  options: undefined,
  bindings: [],
  sql: 'PRAGMA table_info(writing)',
  output: [Function] }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select "writing".* from "writing"' }
```

not sure if this is expected? 
mostly wondering what the first query _actually_ does and if it is necessary for the response? don't think it is, but am unsure? @tkellen ?

**Comment by tkellen** [comment]
This happens once per model and is cached (to populate the known columns for the table):
https://github.com/endpoints/endpoints/blob/master/src/adapter-bookshelf/index.js#L235-L241

**Comment by ashleygwilliams** [comment]
good to know. thanks for answering :heart:
