### ISSUE TITLE
Missing comma in JSON

### ISSUE THREAD

**Issue by ignacio-mts** [ashleygwilliams/ashleygwilliams.github.io#25]
Hi, nice meeting you. I loved your page, but when I visually sent a GET to http://ashleygwilliams.github.io/ I got a few syntax error :)

I think there's a missing comma right after "engineer/educator".

```
"data": [{
    "type": "engineer/educator"
    "id": 666,
    "name": "ashley g. williams",
...
```

**Comment by ashleygwilliams** [comment]
hi! thanks, you are right :) want to submit a PR?

**Comment by ignacio-mts** [comment]
Done. This is my first PR ever, just let me know if I missed anything.

**Comment by ashleygwilliams** [comment]
solved by https://github.com/ashleygwilliams/ashleygwilliams.github.io/pull/26. thanks!
