### ISSUE TITLE
Explorer doesn't work for other domains

### ISSUE THREAD

**Issue by steveklabnik** [ashleygwilliams/ashleygwilliams.github.io#7]
From `/users/1`, the data contains `"github": "https://www.github.com/ashleygwilliams",` so trying to explore to it: 

```
NS_ERROR_MALFORMED_URI:  api-browser.js:26
"http://45.55.231.22:8080htps://www.github.com/ashleygwilliams"
```

Iceweasel 31.5.3

**Comment by ashleygwilliams** [comment]
it shouldn't work. it's only meant to explore the API. the error msg is bad tho.
solved with 57d09959f66edde5f142b2554a45d7a304acf2cd.
